@startuml

skinparam backgroundColor #1E1E1E
skinparam packageStyle folder
skinparam shadowing false
skinparam actorStyle awesome

skinparam package {
    BackgroundColor #1E1E1E
    BorderColor #D4A017
    RoundCorner 10
}

skinparam usecase {
    BackgroundColor #2B2B2B
    BorderColor #D4A017
    FontColor #F5C542
    ArrowColor #D4A017
}

skinparam ArrowColor #D4A017
skinparam defaultFontColor #F5C542


actor Cliente
participant Frontend
participant "API Gateway" as API
participant "Citas Service" as Citas
database "DB Citas" as DB

Cliente -> Frontend : Agenda cita
Frontend -> API : POST /citas
API -> Citas : Registrar cita
Citas -> DB : Guardar cita
DB --> Citas : OK
Citas --> API : Cita confirmada
API --> Frontend : Mostrar comprobante
Frontend --> Cliente : Cita agendada

@enduml